version: "3.8"

services:
  django:
    container_name: django
    build:
      context: ./django
    image: trinity/django
    restart: always
    ports:
      - "8000-8020:8000-8020"
    volumes:
      - django:/etc/develop
    env_file:
      - django/.env
    networks:
      - django-net
      - postgres-net
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    build:
      context: ./postgres
    image: trinity/postgres
    restart: always
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - postgres/.env
    networks:
      - postgres-net

volumes:
  django:
    name: "django"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/gpanico/Desktop/data/django"
  postgres:
    name: "postgres"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/gpanico/Desktop/data/postgres"

networks:
  django-net:
    name: "django-net"

  postgres-net:
    name: "postgres-net"
