# Generated by Django 5.0 on 2023-12-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(db_column='active', db_comment='False when user is banned', default=True),
        ),
    ]
