# Generated by Django 4.2.7 on 2023-12-11 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_column='username', max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z0-9!?*@$~_-]{5,32}$')])),
                ('email', models.EmailField(db_column='email', max_length=320, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('role', models.CharField(choices=[('A', 'admin'), ('M', 'mod'), ('U', 'user')], db_column='role', default='U', max_length=1)),
                ('active', models.BooleanField(db_column='active', db_comment='False when user is banned', default=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
