# Generated by Django 5.0 on 2023-12-23 10:32

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthdate',
            field=models.DateField(db_column='birthdate', null=True, validators=[accounts.validators.validate_birthdate]),
        ),
    ]
