# Generated by Django 5.0 on 2023-12-23 11:03

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userinfo_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthdate',
            field=models.DateField(blank=True, db_column='birthdate', null=True, validators=[accounts.validators.validate_birthdate]),
        ),
    ]
