# Generated by Django 5.0 on 2023-12-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userinfo_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='picture',
            field=models.FilePathField(blank=True, db_column='picture', null=True, path='/tmp/images', recursive=True),
        ),
    ]
