# Generated by Django 5.0 on 2023-12-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userinfo_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(db_column='verified', db_comment='True when email is verified', default=False),
        ),
    ]
