# Generated by Django 5.0 on 2024-01-09 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTFA',
            fields=[
                ('user', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_tfa', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('otp_token', models.CharField(blank=True, db_column='otp_token', default='', max_length=32)),
                ('url_token', models.CharField(blank=True, db_column='url_token', default='', max_length=36)),
                ('type', models.CharField(blank=True, choices=[('SW', 'Software Token'), ('EM', 'Email Token'), ('sw', 'Activating Software Token'), ('em', 'Activating Email Token'), ('', 'None ')], db_column='type', default='', max_length=2)),
            ],
            options={
                'db_table': 'user_tfa',
            },
        ),
    ]
