# Generated by Django 5.0 on 2024-01-04 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertwofactorauth',
            name='user',
            field=models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_tfa', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
