# Generated by Django 5.0 on 2023-12-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JwtToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_column='token', max_length=32, unique=True)),
                ('exp', models.DateTimeField(db_column='exp')),
            ],
            options={
                'db_table': 'jwt_token',
            },
        ),
    ]
