# Generated by Django 5.0 on 2023-12-30 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokens',
            name='email_token',
            field=models.CharField(blank=True, db_column='email_token', default='', max_length=36, validators=[django.core.validators.MinValueValidator(36, message='Too short token')]),
        ),
    ]
