# Generated by Django 5.0 on 2023-12-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0002_alter_usertokens_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokens',
            name='email_token',
            field=models.CharField(blank=True, db_column='email_token', default='', max_length=36),
        ),
    ]
