# Generated by Django 5.0 on 2023-12-30 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0003_alter_usertokens_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertokens',
            name='password_token',
            field=models.CharField(blank=True, db_column='password_token', default='', max_length=36, validators=[django.core.validators.MinLengthValidator(36, message='Too short token')]),
        ),
    ]
