# Generated by Django 4.2.7 on 2023-12-11 13:43

import accounts.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, db_column='first_name', max_length=32, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z -]{1,32}$')])),
                ('last_name', models.CharField(blank=True, db_column='last_name', max_length=32, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z -]{1,32}$')])),
                ('birthdate', models.DateField(db_column='birthdate', null=True, validators=[accounts.validators.validate_birthdate])),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='date_joined')),
                ('picture', models.FilePathField(db_column='picture', null=True, path='/tmp/images', recursive=True)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
